# Generated by Django 6.0.1 on 2026-02-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_setting_alter_invitation_expires_at_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
